<?php
    $title = 'Listar Categorias';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p> 
    <a class="btn btn-primary btn-adicionar" role="button"  href="<?php echo $this->url('categories', array('action'=>'add'));?>">Adicionar Categoria</a>
</p>

<table class="table">
<tr>
    <th>Id</th>
    <th>Nome da Categoria</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($categories as $category) : ?>
<tr>
    <td><?php echo $this->escapeHtml($category->id_categoria_planejamento);?></td>
    <td><?php echo $this->escapeHtml($category->nome_categoria);?></td>

    <td>
        <a class="btn btn-warning" role="button" href="<?php echo $this->url('categories',
            array('action'=>'edit', 'id' => $category->id_categoria_planejamento));?>">Edit</a>
        <a class="btn btn-danger" role="button" href="<?php echo $this->url('categories',
            array('action'=>'delete', 'id' => $category->id_categoria_planejamento));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
