<div class="jumbotron" style="margin-top: 22px;">
    <h1  style="font-size:40px;">Seja Bem vindo ao teste do <span class="zf-green">Rodrigo Karwinski!</span> </h1>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Para me conhecer um pouco mais você pode acessar:</h3>
            </div>
            <div class="panel-body">
                <h4>Mais informações sobre minhas experiencias profissionais</h4>
                <p>Meu LinkedIn: <a href="https://www.linkedin.com/in/rodrigokarwinski/" target="_blank">Rodrigo Karwinski</a></p>
                
                <h4>Ou ate ver mais alguns codigos como esse</h4>
                <p>Meu GitHub: <a href="https://github.com/rkarwinski/" target="_blank">rkarwinski</a></p>
            </div>
        </div>
    </div>

</div>
